import 'package:flutter/material.dart';
import 'package:podcast_search/podcast_search.dart';

enum FetchState {
  unfetched,
  fetching,
  fetched,
  error,
}

extension DateTimeExt on DateTime {
  static const Map<int, String> monthDic = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
  };

  String get displayFormat {
    final year = this.year.toString();
    final month = monthDic[this.month];
    final day = this.day.toString();
    return "$year $month $day";
  }
}

extension DurationExt on Duration {
  String get ms {
    final minutes = inMinutes;
    final seconds = inSeconds - (inMinutes * 60);
    return "$minutes:$seconds";
  }
}

MaterialColor letterToMateriaColor(String letter) {
  final x = letter.codeUnits.first;
  const int oldMin = 0;
  const int oldMax = 150;
  const int newMin = 0;
  const int newMax = 17;
  int newNum =
      ((x - oldMin) * (newMax - newMin) / (oldMax - oldMin) + newMin).round();
  if (newNum > 18) {
    newNum = 17;
  } else if (newNum < 0) {
    newNum = 0;
  }
  return Colors.primaries[newNum];
}

const Map<String, Country> countryCodeDict = {
  "AF": Country.afghanistan,
  "AX": Country.alandislands,
  "AL": Country.albania,
  "DZ": Country.algeria,
  "AS": Country.americansamoa,
  "AD": Country.andorra,
  "AO": Country.angolia,
  "AI": Country.anguilla,
  "AQ": Country.antarctica,
  "AG": Country.antiguaandbarbuda,
  "AR": Country.argentina,
  "AM": Country.armenia,
  "AW": Country.aruba,
  "AU": Country.australia,
  "AT": Country.austria,
  "AZ": Country.azerbaijan,
  "BS": Country.bahamas,
  "BH": Country.bahrain,
  "BD": Country.bangladesh,
  "BB": Country.barbados,
  "BY": Country.belarus,
  "BE": Country.belgium,
  "BZ": Country.belize,
  "BJ": Country.benin,
  "BM": Country.bermuda,
  "BT": Country.bhutan,
  "BO": Country.bolivia,
  "BQ": Country.bonaire,
  "BA": Country.bosniaAndHerzegovina,
  "BW": Country.botswana,
  "BV": Country.bouvetisland,
  "BR": Country.brazil,
  "IO": Country.britishIndianOceanTerrirory,
  "BN": Country.bruneiDarussalam,
  "BG": Country.bulgaria,
  "BF": Country.burkinafaso,
  "BI": Country.burundi,
  "CV": Country.caboverde,
  "KH": Country.cambodia,
  "CM": Country.cameroon,
  "CA": Country.canada,
  "KY": Country.caymanIslands,
  "CF": Country.centralAfricanRepublic,
  "TD": Country.chad,
  "CL": Country.chile,
  "CN": Country.china,
  "CX": Country.christmasIsland,
  "CC": Country.cocosIslands,
  "CO": Country.colombia,
  "KM": Country.comoros,
  "CG": Country.congo,
  "CD": Country.congoDemocraticRepublicof,
  "CK": Country.cookIslands,
  "CR": Country.costarica,
  "CI": Country.coteDivoire,
  "HR": Country.croatia,
  "CU": Country.cuba,
  "CW": Country.curacao,
  "CY": Country.cyprus,
  "CZ": Country.czechia,
  "DK": Country.denmark,
  "DJ": Country.djibouti,
  "DM": Country.dominica,
  "DO": Country.dominicanRepublic,
  "EC": Country.ecuador,
  "EG": Country.egypt,
  "SV": Country.elSalvador,
  "GQ": Country.equatorialGuinea,
  "ER": Country.eritrea,
  "EE": Country.estonia,
  "ET": Country.ethiopia,
  "FK": Country.falklandIslands,
  "FO": Country.faroeIslands,
  "FJ": Country.fiji,
  "FI": Country.finland,
  "FR": Country.france,
  "GF": Country.frenchGuiana,
  "PF": Country.frenchPolynesia,
  "TF": Country.frenchSouthernTerritories,
  "GA": Country.gabon,
  "GM": Country.gambia,
  "GE": Country.georgia,
  "DE": Country.germany,
  "GH": Country.ghana,
  "GI": Country.gibraltar,
  "GR": Country.greece,
  "GL": Country.greenland,
  "GD": Country.grenada,
  "GP": Country.guadeloupe,
  "GU": Country.guam,
  "GT": Country.guatemala,
  "GG": Country.guernsey,
  "GN": Country.guinea,
  "GW": Country.guineaBissau,
  "GY": Country.guyana,
  "HT": Country.haiti,
  "HM": Country.heardIslandAndMcDonaldIslands,
  "HN": Country.honduras,
  "HK": Country.hongKong,
  "HU": Country.hungary,
  "IS": Country.iceland,
  "IN": Country.india,
  "ID": Country.indonesia,
  "IR": Country.iran,
  "IQ": Country.iraq,
  "IE": Country.ireland,
  "IM": Country.isleOfMan,
  "IL": Country.israel,
  "IT": Country.italy,
  "JM": Country.jamaica,
  "JP": Country.japan,
  "JE": Country.jersey,
  "JO": Country.jordan,
  "KZ": Country.kazakhstan,
  "KE": Country.kenya,
  "KI": Country.kiribati,
  "KP": Country.northKorea,
  "KR": Country.southKorea,
  "KW": Country.kuwait,
  "KG": Country.kyrgyzstan,
  "LA": Country.laos,
  "LV": Country.latvia,
  "LB": Country.lebanon,
  "LS": Country.lesotho,
  "LR": Country.liberia,
  "LY": Country.libya,
  "LI": Country.liechtenstein,
  "LT": Country.lithuania,
  "LU": Country.luxembourg,
  "MO": Country.macao,
  "MG": Country.madagascar,
  "MW": Country.malawi,
  "MY": Country.malaysia,
  "MV": Country.maldives,
  "ML": Country.mali,
  "MT": Country.malta,
  "MH": Country.marshallIslands,
  "MQ": Country.martinique,
  "MR": Country.mauritania,
  "MU": Country.mauritius,
  "YT": Country.mayotte,
  "MX": Country.mexico,
  "FM": Country.micronesia,
  "MD": Country.moldova,
  "MC": Country.monaco,
  "MN": Country.mongolia,
  "ME": Country.montenegro,
  "MS": Country.montserrat,
  "MA": Country.morocco,
  "MZ": Country.mozambique,
  "MM": Country.myanmar,
  "NA": Country.namibia,
  "NR": Country.nauru,
  "NP": Country.nepal,
  "NL": Country.netherlands,
  "NC": Country.newCaledonia,
  "NZ": Country.newZealand,
  "NI": Country.nicaragua,
  "NE": Country.niger,
  "NG": Country.nigeria,
  "NU": Country.niue,
  "NF": Country.norfolkIsland,
  "MP": Country.northernMarianaIslands,
  "NO": Country.norway,
  "OM": Country.oman,
  "PK": Country.pakistan,
  "PW": Country.palau,
  "PS": Country.palestine,
  "PA": Country.panama,
  "PG": Country.papuaNewGuinea,
  "PY": Country.paraguay,
  "PE": Country.peru,
  "PH": Country.philippines,
  "PN": Country.pitcairn,
  "PL": Country.poland,
  "PT": Country.portugal,
  "PR": Country.puertoRico,
  "QA": Country.qatar,
  "MK": Country.macedonia,
  "RO": Country.romania,
  "RU": Country.russianFederation,
  "RW": Country.rwanda,
  "RE": Country.reunion,
  "BL": Country.saintBarthelemy,
  "SH": Country.saintHelena,
  "KN": Country.saintKittsAndNevis,
  "LC": Country.saintLucia,
  "MF": Country.saintMartin,
  "PM": Country.saintPierreAndMiquelon,
  "VC": Country.saintVincentAndTheGrenadines,
  "WS": Country.samoa,
  "SM": Country.sanMarino,
  "ST": Country.saoTomeAndPrincipe,
  "SA": Country.saudiArabia,
  "SN": Country.senegal,
  "RS": Country.serbia,
  "SC": Country.seychelles,
  "SL": Country.sierraLeone,
  "SG": Country.singapore,
  "SX": Country.sintMaarten,
  "SK": Country.slovakia,
  "SI": Country.slovenia,
  "SB": Country.solomonIslands,
  "SO": Country.somalia,
  "ZA": Country.southAfrica,
  "GS": Country.southGeorgiaAndTheSouthSandwichIslands,
  "SS": Country.southSudan,
  "ES": Country.spain,
  "LK": Country.sriLanka,
  "SD": Country.sudan,
  "SR": Country.suriname,
  "SJ": Country.svalbardAndJanMayen,
  "SE": Country.sweden,
  "CH": Country.switzerland,
  "SY": Country.syrianArabRepublic,
  "TW": Country.taiwan,
  "TJ": Country.tajikistan,
  "TZ": Country.tanzania,
  "TH": Country.thailand,
  "TL": Country.timorLeste,
  "TG": Country.togo,
  "TK": Country.tokelau,
  "TO": Country.tonga,
  "TT": Country.trinidadAndTobago,
  "TN": Country.tunisia,
  "TR": Country.turkey,
  "TM": Country.turkmenistan,
  "TC": Country.turksAndCaicosIslands,
  "TV": Country.tuvalu,
  "UG": Country.uganda,
  "UA": Country.ukraine,
  "AE": Country.unitedArabEmirates,
  "GB": Country.unitedKingdom,
  "US": Country.unitedStates,
  "UM": Country.unitedStatesMinorOutlyingIslands,
  "UY": Country.uruguay,
  "UZ": Country.uzbekistan,
  "VU": Country.vanuatu,
  "VE": Country.venezuela,
  "VN": Country.vietNam,
  "VG": Country.britishVirginIslands,
  "VI": Country.usVirginIslands,
  "WF": Country.wallisAndFutuna,
  "EH": Country.westernSahara,
  "YE": Country.yemen,
  "ZM": Country.zambia,
  "ZW": Country.zimbabwe
};
